export type IconName = 'play' | 'pause' | 'stop';

/** 조작 버튼 아이콘 12×12. `I`가 찍는 자리, `.`은 비움 */
export const ICONS: Record<IconName, readonly string[]> = {
  play: [
    '...I........',
    '...II.......',
    '...III......',
    '...IIII.....',
    '...IIIII....',
    '...IIIIII...',
    '...IIIIII...',
    '...IIIII....',
    '...IIII.....',
    '...III......',
    '...II.......',
    '...I........',
  ],
  pause: [
    '..III..III..',
    '..III..III..',
    '..III..III..',
    '..III..III..',
    '..III..III..',
    '..III..III..',
    '..III..III..',
    '..III..III..',
    '..III..III..',
    '..III..III..',
    '..III..III..',
    '..III..III..',
  ],
  stop: [
    '............',
    '............',
    '..IIIIIIII..',
    '..IIIIIIII..',
    '..IIIIIIII..',
    '..IIIIIIII..',
    '..IIIIIIII..',
    '..IIIIIIII..',
    '..IIIIIIII..',
    '..IIIIIIII..',
    '............',
    '............',
  ],
};
